package com.example.fortunecookie;

import com.example.fortunecookie.entity.Fortune;
import com.example.fortunecookie.entity.FortuneCategory;
import com.example.fortunecookie.repository.FortuneRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@RequiredArgsConstructor
public class DataInitializer implements ApplicationRunner {

    private final FortuneRepository fortuneRepository;

    @Override
    public void run(ApplicationArguments args) {
        if (fortuneRepository.count() > 0) return;

        List<Fortune> fortunes = List.of(
            // 행운
            new Fortune("오늘은 뜻밖의 기쁜 소식이 찾아올 것입니다.", FortuneCategory.LUCK),
            new Fortune("작은 행운이 하루 종일 당신 곁에 머물 것입니다.", FortuneCategory.LUCK),
            new Fortune("오늘 당신이 내리는 선택은 행운을 불러옵니다.", FortuneCategory.LUCK),
            new Fortune("기대하지 않았던 곳에서 좋은 일이 생길 것입니다.", FortuneCategory.LUCK),
            new Fortune("오늘의 작은 시도가 큰 행운의 시작이 됩니다.", FortuneCategory.LUCK),
            new Fortune("행운은 준비된 사람에게 찾아옵니다. 오늘이 바로 그 날입니다.", FortuneCategory.LUCK),
            new Fortune("사소한 곳에서 반짝이는 행운을 발견하게 될 것입니다.", FortuneCategory.LUCK),
            new Fortune("오늘은 특별히 운이 좋은 날입니다. 용기를 내세요.", FortuneCategory.LUCK),
            new Fortune("당신의 직감을 믿으세요. 오늘은 틀리지 않습니다.", FortuneCategory.LUCK),
            new Fortune("오늘 만나는 인연이 당신에게 행운을 가져다줄 것입니다.", FortuneCategory.LUCK),
            new Fortune("복권보다 귀한 행운이 오늘 당신 손에 있습니다.", FortuneCategory.LUCK),
            new Fortune("오늘은 잃어버렸던 것을 되찾게 되는 날입니다.", FortuneCategory.LUCK),
            new Fortune("행운의 별이 오늘 당신 머리 위에서 빛나고 있습니다.", FortuneCategory.LUCK),
            new Fortune("오늘 우연히 마주치는 것들이 모두 좋은 신호입니다.", FortuneCategory.LUCK),
            new Fortune("당신이 뿌린 씨앗이 오늘 드디어 싹을 틔웁니다.", FortuneCategory.LUCK),
            new Fortune("막혀 있던 일이 오늘을 기점으로 술술 풀릴 것입니다.", FortuneCategory.LUCK),
            new Fortune("오늘은 어디서나 환영받는 하루가 될 것입니다.", FortuneCategory.LUCK),
            new Fortune("행운은 당신이 웃을 때 더 크게 찾아옵니다.", FortuneCategory.LUCK),
            new Fortune("오늘 당신의 선택은 모두 옳습니다. 자신감을 가지세요.", FortuneCategory.LUCK),
            new Fortune("작은 친절이 큰 행운이 되어 돌아오는 날입니다.", FortuneCategory.LUCK),
            // 성공
            new Fortune("꾸준함이 결국 빛을 발하는 날이 다가오고 있습니다.", FortuneCategory.SUCCESS),
            new Fortune("오늘의 노력은 반드시 내일의 결실로 돌아옵니다.", FortuneCategory.SUCCESS),
            new Fortune("당신이 목표로 한 것이 손에 닿을 만큼 가까워졌습니다.", FortuneCategory.SUCCESS),
            new Fortune("포기하지 않은 당신에게 성공이 손짓하고 있습니다.", FortuneCategory.SUCCESS),
            new Fortune("오늘 한 걸음이 정상을 향한 가장 중요한 발걸음입니다.", FortuneCategory.SUCCESS),
            new Fortune("당신의 재능이 오늘 드디어 주목받게 될 것입니다.", FortuneCategory.SUCCESS),
            new Fortune("성공은 먼 곳에 있지 않습니다. 오늘 당신 바로 앞에 있습니다.", FortuneCategory.SUCCESS),
            new Fortune("당신이 준비해온 것들이 오늘 빛을 발합니다.", FortuneCategory.SUCCESS),
            new Fortune("어렵다고 생각했던 일이 오늘은 놀랍도록 쉽게 풀립니다.", FortuneCategory.SUCCESS),
            new Fortune("당신의 노력을 알아보는 사람이 오늘 나타납니다.", FortuneCategory.SUCCESS),
            new Fortune("오늘은 중요한 결정을 내리기에 최적의 날입니다.", FortuneCategory.SUCCESS),
            new Fortune("시작이 반입니다. 오늘 바로 시작하세요.", FortuneCategory.SUCCESS),
            new Fortune("당신의 아이디어는 생각보다 훨씬 가치 있습니다.", FortuneCategory.SUCCESS),
            new Fortune("오늘은 새로운 기회의 문이 활짝 열리는 날입니다.", FortuneCategory.SUCCESS),
            new Fortune("당신이 원하는 자리가 오늘 당신을 기다리고 있습니다.", FortuneCategory.SUCCESS),
            new Fortune("완벽하지 않아도 괜찮습니다. 오늘의 시도가 성공의 씨앗입니다.", FortuneCategory.SUCCESS),
            new Fortune("오늘 당신이 만나는 기회를 놓치지 마세요.", FortuneCategory.SUCCESS),
            new Fortune("당신의 끈기가 드디어 결실을 맺을 시간이 왔습니다.", FortuneCategory.SUCCESS),
            new Fortune("실패가 아닙니다. 오늘은 성공으로 가는 연습이었습니다.", FortuneCategory.SUCCESS),
            new Fortune("오늘 당신이 내린 결정이 훗날 가장 잘한 선택이 될 것입니다.", FortuneCategory.SUCCESS),
            // 인간관계
            new Fortune("오늘 만나는 사람이 평생의 인연이 될 수도 있습니다.", FortuneCategory.RELATIONSHIP),
            new Fortune("먼저 손을 내밀어 보세요. 오늘은 그 용기가 통합니다.", FortuneCategory.RELATIONSHIP),
            new Fortune("오랫동안 연락하지 못했던 사람에게 연락해 보세요.", FortuneCategory.RELATIONSHIP),
            new Fortune("당신을 진심으로 응원하는 사람이 가까이에 있습니다.", FortuneCategory.RELATIONSHIP),
            new Fortune("오늘은 오해가 풀리고 관계가 회복되는 날입니다.", FortuneCategory.RELATIONSHIP),
            new Fortune("진심 어린 한마디가 누군가의 하루를 바꿔줄 것입니다.", FortuneCategory.RELATIONSHIP),
            new Fortune("당신 주변에 당신을 아끼는 사람들이 생각보다 많습니다.", FortuneCategory.RELATIONSHIP),
            new Fortune("새로운 사람과의 만남이 새로운 세계를 열어줄 것입니다.", FortuneCategory.RELATIONSHIP),
            new Fortune("오늘 베푼 친절이 돌고 돌아 당신에게 따뜻하게 돌아옵니다.", FortuneCategory.RELATIONSHIP),
            new Fortune("함께하면 더 강해지는 날입니다. 혼자 고민하지 마세요.", FortuneCategory.RELATIONSHIP),
            new Fortune("오늘 당신의 말 한마디가 누군가에게 큰 힘이 됩니다.", FortuneCategory.RELATIONSHIP),
            new Fortune("믿음직한 사람이 당신 곁에서 든든하게 지켜주고 있습니다.", FortuneCategory.RELATIONSHIP),
            new Fortune("오늘은 소중한 사람에게 마음을 표현하기 좋은 날입니다.", FortuneCategory.RELATIONSHIP),
            new Fortune("갈등이 있던 관계가 오늘을 기점으로 좋아질 것입니다.", FortuneCategory.RELATIONSHIP),
            new Fortune("당신의 진심이 상대방에게 오늘 정확하게 전달됩니다.", FortuneCategory.RELATIONSHIP),
            new Fortune("오늘 우연히 만난 사람과 뜻밖의 공감대를 형성하게 됩니다.", FortuneCategory.RELATIONSHIP),
            new Fortune("당신의 웃음이 오늘 주변 사람들을 행복하게 합니다.", FortuneCategory.RELATIONSHIP),
            new Fortune("좋은 사람과의 대화가 오늘 당신에게 새로운 시각을 줍니다.", FortuneCategory.RELATIONSHIP),
            new Fortune("오늘은 도움을 요청하기 좋은 날입니다. 혼자 짊어지지 마세요.", FortuneCategory.RELATIONSHIP),
            new Fortune("소중한 인연이 더 깊어지는 하루가 될 것입니다.", FortuneCategory.RELATIONSHIP),
            // 사랑
            new Fortune("사랑은 지금 이 순간에도 당신 주변에 가득합니다.", FortuneCategory.LOVE),
            new Fortune("오늘 설레는 감정에 솔직해져 보세요.", FortuneCategory.LOVE),
            new Fortune("마음속에 담아두었던 말을 오늘 꺼내보세요. 잘 될 것입니다.", FortuneCategory.LOVE),
            new Fortune("사랑하는 사람과 함께하는 시간이 오늘 특별하게 빛납니다.", FortuneCategory.LOVE),
            new Fortune("오늘 뜻밖의 고백이나 사랑의 표현을 받을 수 있습니다.", FortuneCategory.LOVE),
            new Fortune("오래된 인연에 새로운 감정이 피어나는 날입니다.", FortuneCategory.LOVE),
            new Fortune("당신을 진심으로 사랑하는 사람이 오늘 더 선명하게 보일 것입니다.", FortuneCategory.LOVE),
            new Fortune("첫눈에 반하는 만남이 오늘 찾아올 수 있습니다.", FortuneCategory.LOVE),
            new Fortune("사랑하는 사람에게 먼저 연락해보세요. 좋은 일이 생깁니다.", FortuneCategory.LOVE),
            new Fortune("오늘은 당신의 매력이 평소보다 더욱 빛나는 날입니다.", FortuneCategory.LOVE),
            new Fortune("마음을 열면 사랑이 들어올 자리가 생깁니다.", FortuneCategory.LOVE),
            new Fortune("오늘 받는 사랑을 있는 그대로 받아들이세요.", FortuneCategory.LOVE),
            new Fortune("당신 곁에 있는 사람이 얼마나 소중한지 오늘 다시 느끼게 됩니다.", FortuneCategory.LOVE),
            new Fortune("사랑은 당신이 생각하는 것보다 훨씬 가까이 있습니다.", FortuneCategory.LOVE),
            new Fortune("오늘은 관계에서 한 걸음 더 나아가기 좋은 날입니다.", FortuneCategory.LOVE),
            new Fortune("당신의 진심 어린 사랑이 오늘 상대방의 마음을 움직입니다.", FortuneCategory.LOVE),
            new Fortune("오늘 함께하는 시간이 평생 기억에 남는 추억이 될 것입니다.", FortuneCategory.LOVE),
            new Fortune("사랑받기 위해 완벽할 필요가 없습니다. 지금 당신 그대로 충분합니다.", FortuneCategory.LOVE),
            new Fortune("오늘은 사랑하는 사람에게 작은 선물을 건네보세요.", FortuneCategory.LOVE),
            new Fortune("감사한 마음을 표현하는 것이 오늘 사랑을 더 깊게 합니다.", FortuneCategory.LOVE),
            // 건강
            new Fortune("오늘은 몸과 마음을 함께 돌보는 하루를 만들어보세요.", FortuneCategory.HEALTH),
            new Fortune("작은 산책 하나가 오늘 당신에게 큰 활력을 줄 것입니다.", FortuneCategory.HEALTH),
            new Fortune("충분한 휴식이 내일의 에너지가 됩니다. 오늘은 쉬어도 됩니다.", FortuneCategory.HEALTH),
            new Fortune("물을 자주 마시고 깊게 숨을 쉬는 하루를 보내세요.", FortuneCategory.HEALTH),
            new Fortune("당신의 몸이 오늘 당신에게 쉬어가라는 신호를 보내고 있습니다.", FortuneCategory.HEALTH),
            new Fortune("오늘 몸을 움직이면 기분이 눈에 띄게 좋아질 것입니다.", FortuneCategory.HEALTH),
            new Fortune("마음의 평화가 건강의 시작입니다. 오늘 잠시 명상해 보세요.", FortuneCategory.HEALTH),
            new Fortune("규칙적인 식사가 오늘 당신에게 중요합니다.", FortuneCategory.HEALTH),
            new Fortune("당신의 건강은 당신이 생각하는 것보다 훨씬 좋은 상태입니다.", FortuneCategory.HEALTH),
            new Fortune("오늘 오래된 걱정을 내려놓으면 몸도 가벼워집니다.", FortuneCategory.HEALTH),
            new Fortune("좋아하는 음식을 오늘 마음껏 즐겨보세요. 행복도 건강입니다.", FortuneCategory.HEALTH),
            new Fortune("긍정적인 생각이 오늘 당신의 면역력을 높여줍니다.", FortuneCategory.HEALTH),
            new Fortune("오늘은 일찍 잠자리에 들어 충전하는 하루로 만들어 보세요.", FortuneCategory.HEALTH),
            new Fortune("스트레스를 잠시 옆에 두고 지금 이 순간을 즐기세요.", FortuneCategory.HEALTH),
            new Fortune("오늘 자신의 몸에 감사하는 마음을 가져보세요.", FortuneCategory.HEALTH),
            new Fortune("꾸준함이 건강을 만듭니다. 오늘도 좋은 습관을 이어가세요.", FortuneCategory.HEALTH),
            new Fortune("따뜻한 차 한 잔이 오늘 당신의 마음을 부드럽게 녹여줄 것입니다.", FortuneCategory.HEALTH),
            new Fortune("햇빛을 쬐며 걷는 것만으로도 오늘 하루가 달라집니다.", FortuneCategory.HEALTH),
            new Fortune("오늘은 무리하지 말고 자신의 페이스를 지키세요.", FortuneCategory.HEALTH),
            new Fortune("건강한 하루가 쌓여 건강한 인생이 됩니다. 오늘도 잘 하고 있습니다.", FortuneCategory.HEALTH),
            // 도전
            new Fortune("두려움은 성장의 신호입니다. 오늘 한 발 내딛어 보세요.", FortuneCategory.CHALLENGE),
            new Fortune("불가능해 보였던 일이 오늘 가능해지는 순간이 옵니다.", FortuneCategory.CHALLENGE),
            new Fortune("실패를 두려워하지 마세요. 오늘의 도전이 내일의 자랑이 됩니다.", FortuneCategory.CHALLENGE),
            new Fortune("오늘은 새로운 것을 배우기 가장 좋은 날입니다.", FortuneCategory.CHALLENGE),
            new Fortune("편안함을 벗어날 때 진짜 성장이 시작됩니다.", FortuneCategory.CHALLENGE),
            new Fortune("오늘 처음 해보는 것에 도전해 보세요. 생각보다 잘 될 것입니다.", FortuneCategory.CHALLENGE),
            new Fortune("당신 안에는 당신도 모르는 능력이 숨어 있습니다.", FortuneCategory.CHALLENGE),
            new Fortune("어제와 다른 길을 걸어보세요. 새로운 세계가 펼쳐집니다.", FortuneCategory.CHALLENGE),
            new Fortune("오늘 아무도 하지 않은 것을 해보세요. 당신이 첫 번째가 될 수 있습니다.", FortuneCategory.CHALLENGE),
            new Fortune("조금 부족해도 괜찮습니다. 시작 자체가 이미 훌륭합니다.", FortuneCategory.CHALLENGE),
            new Fortune("오늘의 도전이 한 달 뒤 당신을 완전히 바꿔놓을 것입니다.", FortuneCategory.CHALLENGE),
            new Fortune("당신이 망설이는 그 일, 오늘이 바로 시작하기 좋은 때입니다.", FortuneCategory.CHALLENGE),
            new Fortune("변화는 언제나 불편함에서 시작됩니다. 오늘 그 불편함을 반겨보세요.", FortuneCategory.CHALLENGE),
            new Fortune("한 번만 더 시도해 보세요. 이번이 바로 그 순간일 수 있습니다.", FortuneCategory.CHALLENGE),
            new Fortune("오늘 포기하지 않은 당신을 미래의 당신이 고마워할 것입니다.", FortuneCategory.CHALLENGE),
            new Fortune("작은 도전들이 모여 위대한 삶이 됩니다.", FortuneCategory.CHALLENGE),
            new Fortune("오늘 배운 것이 오래도록 빛나는 자산이 될 것입니다.", FortuneCategory.CHALLENGE),
            new Fortune("당신의 가능성은 당신이 생각하는 것보다 훨씬 큽니다.", FortuneCategory.CHALLENGE),
            new Fortune("오늘은 두 번째 기회가 찾아오는 날입니다. 이번엔 잡으세요.", FortuneCategory.CHALLENGE),
            new Fortune("한계라고 생각한 것이 오늘 무너집니다.", FortuneCategory.CHALLENGE),
            // 긍정
            new Fortune("오늘 하루도 충분히 잘 살고 있습니다.", FortuneCategory.POSITIVITY),
            new Fortune("지금 이 순간이 당신 인생에서 가장 빛나는 시간 중 하나입니다.", FortuneCategory.POSITIVITY),
            new Fortune("당신은 생각보다 훨씬 강한 사람입니다.", FortuneCategory.POSITIVITY),
            new Fortune("오늘 거울을 보고 자신에게 미소 지어 보세요.", FortuneCategory.POSITIVITY),
            new Fortune("지금 당신이 있는 자리가 가장 좋은 자리입니다.", FortuneCategory.POSITIVITY),
            new Fortune("오늘 하루의 끝에는 반드시 좋은 일이 기다리고 있습니다.", FortuneCategory.POSITIVITY),
            new Fortune("당신의 존재 자체가 누군가에게 큰 힘이 됩니다.", FortuneCategory.POSITIVITY),
            new Fortune("오늘은 과거의 짐을 내려놓고 가볍게 걸어보세요.", FortuneCategory.POSITIVITY),
            new Fortune("비가 온 뒤에 더 맑은 하늘이 펼쳐지듯, 좋은 날이 오고 있습니다.", FortuneCategory.POSITIVITY),
            new Fortune("작은 것에서 기쁨을 찾는 당신의 마음이 오늘도 아름답습니다.", FortuneCategory.POSITIVITY),
            new Fortune("오늘 일어난 모든 일은 당신을 더 강하게 만들기 위한 것입니다.", FortuneCategory.POSITIVITY),
            new Fortune("지금 느끼는 감정이 어떤 것이든, 모두 괜찮습니다.", FortuneCategory.POSITIVITY),
            new Fortune("당신의 가치는 성과가 아닌 존재 자체에서 나옵니다.", FortuneCategory.POSITIVITY),
            new Fortune("오늘의 작은 감사가 내일의 큰 행복을 만듭니다.", FortuneCategory.POSITIVITY),
            new Fortune("모든 것이 제자리를 찾아가고 있습니다. 믿어 보세요.", FortuneCategory.POSITIVITY),
            new Fortune("오늘 당신이 느끼는 불안은 곧 사라질 것입니다.", FortuneCategory.POSITIVITY),
            new Fortune("지금 잘하고 있습니다. 스스로를 믿어 주세요.", FortuneCategory.POSITIVITY),
            new Fortune("당신은 당신 자신의 가장 좋은 친구가 될 수 있습니다.", FortuneCategory.POSITIVITY),
            new Fortune("오늘은 그냥 흘러가는 대로 두어도 괜찮은 날입니다.", FortuneCategory.POSITIVITY),
            new Fortune("당신이 오늘 느끼는 기쁨이 세상을 조금 더 밝게 만듭니다.", FortuneCategory.POSITIVITY),
            // 재물
            new Fortune("예상치 못한 좋은 소식이 오늘 재물운을 높여줄 것입니다.", FortuneCategory.WEALTH),
            new Fortune("낭비를 줄이는 오늘의 선택이 미래의 풍요를 만듭니다.", FortuneCategory.WEALTH),
            new Fortune("오늘은 새로운 수입원을 발견할 수 있는 날입니다.", FortuneCategory.WEALTH),
            new Fortune("기다리던 금전적 문제가 오늘을 기점으로 해결됩니다.", FortuneCategory.WEALTH),
            new Fortune("오늘 재물운이 상승합니다. 작은 기회도 놓치지 마세요.", FortuneCategory.WEALTH),
            new Fortune("절약이 미덕인 날입니다. 오늘 지출을 한 번 점검해 보세요.", FortuneCategory.WEALTH),
            new Fortune("투자한 시간과 노력이 오늘 드디어 수익으로 돌아옵니다.", FortuneCategory.WEALTH),
            new Fortune("작은 돈을 소중히 여기는 태도가 오늘 큰 부를 만드는 시작입니다.", FortuneCategory.WEALTH),
            new Fortune("오늘 좋은 제안을 받게 될 것입니다. 신중하게 검토해 보세요.", FortuneCategory.WEALTH),
            new Fortune("귀인이 오늘 당신에게 중요한 기회를 가져다 줄 것입니다.", FortuneCategory.WEALTH),
            // 창의
            new Fortune("오늘 당신의 창의력은 최고조에 달해 있습니다.", FortuneCategory.CREATIVITY),
            new Fortune("평범한 것에서 특별한 아이디어가 떠오르는 날입니다.", FortuneCategory.CREATIVITY),
            new Fortune("오늘 떠오른 생각을 바로 기록해 두세요. 나중에 큰 가치가 됩니다.", FortuneCategory.CREATIVITY),
            new Fortune("당신의 독창적인 생각이 오늘 주목받게 됩니다.", FortuneCategory.CREATIVITY),
            new Fortune("영감은 예상치 못한 순간에 찾아옵니다. 오늘 눈과 귀를 열어 두세요.", FortuneCategory.CREATIVITY),
            new Fortune("오늘 당신의 손에서 탄생하는 것은 무엇이든 빛납니다.", FortuneCategory.CREATIVITY),
            new Fortune("창의적인 해결책이 오늘 당신에게 찾아옵니다.", FortuneCategory.CREATIVITY),
            new Fortune("당신의 상상력이 오늘 현실을 바꾸는 힘이 됩니다.", FortuneCategory.CREATIVITY),
            new Fortune("오늘 예술적 감수성이 풍부해지는 날입니다.", FortuneCategory.CREATIVITY),
            new Fortune("오래된 문제에 새로운 시각으로 접근하면 해답이 보입니다.", FortuneCategory.CREATIVITY),
            // 여행
            new Fortune("새로운 장소가 오늘 당신에게 신선한 에너지를 줄 것입니다.", FortuneCategory.TRAVEL),
            new Fortune("오늘은 일상에서 벗어나 새로운 경험을 해보기 좋은 날입니다.", FortuneCategory.TRAVEL),
            new Fortune("여행을 계획하고 있다면 오늘이 결정하기 좋은 날입니다.", FortuneCategory.TRAVEL),
            new Fortune("변화는 언제나 새로운 시작을 의미합니다. 오늘을 시작점으로 삼으세요.", FortuneCategory.TRAVEL),
            new Fortune("낯선 길을 걸어보세요. 오늘 새로운 발견이 기다립니다.", FortuneCategory.TRAVEL),
            new Fortune("오늘 하루 루틴을 바꿔보면 뜻밖의 즐거움을 만납니다.", FortuneCategory.TRAVEL),
            new Fortune("오늘의 작은 모험이 평생 기억될 추억이 됩니다.", FortuneCategory.TRAVEL),
            new Fortune("멀리 떠나지 않아도 됩니다. 오늘은 일상 속 소소한 탐험을 즐겨 보세요.", FortuneCategory.TRAVEL),
            new Fortune("변화를 두려워하지 마세요. 오늘 그 문을 열면 환한 빛이 기다립니다.", FortuneCategory.TRAVEL),
            new Fortune("오늘 당신이 경험하는 모든 것이 성장의 양분이 됩니다.", FortuneCategory.TRAVEL),
            // 지혜
            new Fortune("오늘 침묵하는 것이 가장 현명한 선택일 수 있습니다.", FortuneCategory.WISDOM),
            new Fortune("답은 멀리 있지 않습니다. 오늘 내면의 소리에 귀 기울여 보세요.", FortuneCategory.WISDOM),
            new Fortune("오늘은 말보다 듣는 것이 더 큰 지혜를 가져다 줍니다.", FortuneCategory.WISDOM),
            new Fortune("서두르지 마세요. 오늘은 천천히 생각하는 것이 정답입니다.", FortuneCategory.WISDOM),
            new Fortune("지혜로운 판단이 오늘 당신을 옳은 방향으로 이끕니다.", FortuneCategory.WISDOM),
            new Fortune("오늘 배우는 교훈이 평생의 지침이 될 것입니다.", FortuneCategory.WISDOM),
            new Fortune("모든 경험에는 이유가 있습니다. 오늘 그 의미를 발견하게 됩니다.", FortuneCategory.WISDOM),
            new Fortune("오늘은 복잡한 것을 단순하게 보는 지혜가 생깁니다.", FortuneCategory.WISDOM),
            new Fortune("당신이 이미 알고 있는 것이 오늘 가장 필요한 답입니다.", FortuneCategory.WISDOM),
            new Fortune("오늘은 직관과 이성 사이에서 균형을 찾게 되는 날입니다.", FortuneCategory.WISDOM),
            // 감사
            new Fortune("오늘 작은 것들에 감사해 보세요. 행복이 더 커집니다.", FortuneCategory.GRATITUDE),
            new Fortune("당신의 일상이 누군가에게는 꿈꾸는 삶입니다.", FortuneCategory.GRATITUDE),
            new Fortune("오늘 하루를 선물로 여겨 보세요. 모든 것이 달리 보입니다.", FortuneCategory.GRATITUDE),
            new Fortune("지금 가진 것들이 오늘 더 소중하게 느껴지는 날입니다.", FortuneCategory.GRATITUDE),
            new Fortune("당신의 평범한 하루가 사실은 특별한 하루입니다.", FortuneCategory.GRATITUDE),
            new Fortune("오늘은 서두르지 말고 천천히 음미하며 살아 보세요.", FortuneCategory.GRATITUDE),
            new Fortune("감사한 마음이 오늘 당신을 더 풍요롭게 만들어 줍니다.", FortuneCategory.GRATITUDE),
            new Fortune("오늘 하루 끝에 세 가지 감사한 일을 떠올려 보세요.", FortuneCategory.GRATITUDE),
            new Fortune("충분히 쉬는 것도 생산적인 일입니다. 오늘은 여유를 허락하세요.", FortuneCategory.GRATITUDE),
            new Fortune("당신이 누리고 있는 것들이 오늘 더욱 빛나 보일 것입니다.", FortuneCategory.GRATITUDE),
            // 긍정 추가
            new Fortune("오늘 하늘을 한 번 올려다 보세요. 마음이 넓어집니다.", FortuneCategory.POSITIVITY),
            new Fortune("걱정의 절반은 일어나지 않습니다. 오늘 마음을 가볍게 하세요.", FortuneCategory.POSITIVITY),
            new Fortune("오늘 당신이 건네는 미소가 세상을 바꿉니다.", FortuneCategory.POSITIVITY),
            new Fortune("오늘은 원하는 것을 구체적으로 상상해 보세요. 이루어집니다.", FortuneCategory.POSITIVITY),
            new Fortune("지금 이 자리에서 최선을 다하는 것이 오늘의 성공입니다.", FortuneCategory.POSITIVITY),
            new Fortune("오늘 운명이 당신 편에서 일하고 있습니다.", FortuneCategory.LUCK),
            new Fortune("당신이 오늘 내리는 모든 결정을 응원합니다.", FortuneCategory.POSITIVITY),
            new Fortune("좋은 하루는 좋은 아침으로 시작됩니다. 오늘을 잘 열었습니다.", FortuneCategory.POSITIVITY),
            new Fortune("오늘의 태양이 당신만을 위해 뜬 것 같은 날입니다.", FortuneCategory.LUCK),
            new Fortune("당신은 이미 충분합니다. 오늘도, 내일도.", FortuneCategory.POSITIVITY)
        );

        fortuneRepository.saveAll(fortunes);
    }
}
